### ISSUE TITLE
Question: how to manage missed CpG values?

### ISSUE THREAD

**Issue by GillianGrayson** [demh/epigenetic_ageing_clock#2]
Hi!

Thank you so much for such a wonderful repository with all types of epigenetic clocks!

May I ask you to clarify a few things?
Some CpGs that are involved in different clock models in some datasets may be missed because of quality control.
How do you solve the problem of restoring the values of these missing CpGs?
1) You don't use CpG data in your clock formulas?
2) Perform imputation of missing values with mean/median values from other datasets?
3) Any other methods?
Do you know how the original authors of the clocks solve this problem?

Thank you very much!

**Comment by demh** [comment]
Hi Gillian!

The methods in 1. and 2. are both used in the field, but there is also evidence that they can affect predictions significantly at the individual level (probably OK for population level analysis if only a few CpG sites missing). If you do 2., I would recommend median imputation that considers the age+sex of the sample. 

I hope this helps. :)

Dani
